version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-volume:/data/db"
  mo2:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2:latest
    env_file:
      - var.env
    environment:
      - qiniuak=${qiniuak}
      - qiniusk=${qiniusk}
      - emailAddr=${emailAddr}
      - emailPass=${emailPass}
    ports:
      - 5001:5001
    depends_on:
      - "mongodb"
    volumes:
      - "./secrets:/app/secrets"
  nginx:
    build: .
    ports:
      - 80:80
